### PR TITLE
Use underscores rather than colons in authorities

### PR DESCRIPTION
**Pull request by simonw**
Refn #290

### CODE REVIEW

**Comment by bryanculbertson** [comment]
@simonw You also need to check where each of them make their ids and fix those too. The id prefix should match the source.

**Comment by simonw** [comment]
Oh I see, places like this: https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/90a242bbe1814f54d63aa84a1b0949f60a88cf4a/vaccine_feed_ingest/runners/az/arcgis/normalize.py#L33-L46

**Comment by simonw** [comment]
I'm testing this by running:

    poetry run vaccine-feed-ingest all-stages

Then I'm going to check all of the generated normalized output to see what their authority values look like.

**Comment by simonw** [comment]
I explored the output a bit in a Jupyter notebook here: https://gist.github.com/simonw/cfa7acf9d9e7ac10696f978016704ef1 - it looks like this does the right thing.

**Review by bryanculbertson — APPROVED** [review]
Thank you!

**Comment by bryanculbertson** [comment]
@simonw I am going to merge this

**Pull request merged**
