### PR TITLE
Add CVS regex.

### PR DESCRIPTION
**Pull request by cdjj**
Solves #85.

### CODE REVIEW

**Comment by cdjj** [comment]
Incidentally, I've got a script that scrapes CVS for which cities have available appointments; would that be useful?

**Comment by cdjj** [comment]
Sure thing --- I've extended it to match variants on CVS Pharmacy.

Re scraper, is there anywhere you'd like me to put it in the code base?  It's not currently a great fit for the fetchers, since it's just listing which cities have availability, not which stores.

**Comment by cdjj** [comment]
Good catch (pun intended), fixed.

**Comment by cdjj** [comment]
FWIW, I just spent a couple minutes poking at CVS's web flow.  It looks like it should be pretty straightforward to build a real fetcher for it (i.e. give it a ZIP code and get locations with availability), I'll try doing that later today.

**Comment by obra** [comment]
we get cvs info nationally from vaccinespotter, so this may not be worth a ton of your time.

**Comment by cdjj** [comment]
ACK.

**Comment by cdjj** [comment]
Done.

**Comment by cdjj** [comment]
Closes #85 .

**Pull request merged**
