### PR TITLE
normalize dc/district

### LINKED ISSUE #428: normalize dc/district
[learn our pipeline: normalize](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#normalize)

Blocked by #401

Normalize existing [`.ndjson`](http://ndjson.org/) records into [the Vaccinate The States data schema](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Normalized-Location-Schema).

Read all files in the directory passed as the second argument (`sys.argv[2]`), transform each record into the normalized schema (filling in as much detail as possible), then output them to new files in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the normalize stage and how to get set up for development!

### Tips

1. Fetch and parse data for this site before you start developing:
    ```sh
    poetry run vaccine-feed-ingest fetch dc/district
    poetry run vaccine-feed-ingest parse dc/district
    ```

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest normalize dc/district
    ```

### Example
[Parsed files for `ak/arcgis`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/ak/arcgis/parsed) are converted to [normalized files](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/ak/arcgis/normalized)

### PR DESCRIPTION
**Pull request by rascalking**
# Normalize district for DC 

| Key Details |
|-|
| Resolves #428 |
State: DC |
Site: district |

## Notes

Pulled in dateparser to get a valid date out of, eg. "May 27".

## Data sample

```json
{"id": "dc_district:5fc514eb48024682b05f5b80136cd4b0", "name": "Arena Stage", "address": {"street1": "1101 6th St SW", "street2": null, "city": "Washington", "state": "DC", "zip": null}, "location": null, "contact": null, "languages": null, "opening_dates": null, "opening_hours": [{"day": "thursday", "opens": "08:00", "closes": "12:00"}, {"day": "friday", "opens": "08:00", "closes": "12:00"}, {"day": "saturday", "opens": "08:00", "closes": "12:00"}, {"day": "sunday", "opens": "08:00", "closes": "12:00"}, {"day": "thursday", "opens": "13:00", "closes": "17:00"}, {"day": "friday", "opens": "13:00", "closes": "17:00"}, {"day": "saturday", "opens": "13:00", "closes": "17:00"}, {"day": "sunday", "opens": "13:00", "closes": "17:00"}], "availability": {"drop_in": true, "appointments": false}, "inventory": null, "access": null, "parent_organization": null, "links": null, "notes": null, "active": null, "source": {"source": "dc_district", "id": "5fc514eb48024682b05f5b80136cd4b0", "fetched_from_uri": "https://coronavirus.dc.gov/vaccinatedc", "fetched_at": "2021-05-07T04:22:13.256079", "published_at": null, "data": {"Walk-Up Site": "Arena Stage", "Address": "1101 6th St SW", "Normal Days / Hours": "Thursday-Sunday \n8am-12pm, 1pm-5pm", "Vaccine": "Pfizer"}}}
{"id": "dc_district:44d04729d81d561d603f7e9952e79908", "name": "Fort Stanton Rec Center", "address": {"street1": "1812 Erie St, SE", "street2": null, "city": "Washington", "state": "DC", "zip": null}, "location": null, "contact": null, "languages": null, "opening_dates": [{"opens": "2021-05-03", "closes": "2021-05-06"}, {"opens": "2021-05-10", "closes": "2021-05-13"}, {"opens": "2021-05-24", "closes": "2021-05-27"}], "opening_hours": null, "availability": {"drop_in": true, "appointments": false}, "inventory": null, "access": null, "parent_organization": null, "links": null, "notes": null, "active": null, "source": {"source": "dc_district", "id": "44d04729d81d561d603f7e9952e79908", "fetched_from_uri": "https://coronavirus.dc.gov/vaccinatedc", "fetched_at": "2021-05-07T04:22:13.256079", "published_at": null, "data": {"Walk-Up Site": "Fort Stanton Rec Center", "Address": "1812 Erie St, SE", "Normal Days / Hours": "May 3 - May 6 and May 10 - May 13 \n9am-1pm \nMay 24 - May 27 \n2pm - 7pm", "Vaccine": "Pfizer"}}}
{"id": "dc_district:e2d5625b5abe386bdc411cf1f6aad670", "name": "Kenilworth Rec Center", "address": {"street1": "4321 Ord St, NE", "street2": null, "city": "Washington", "state": "DC", "zip": null}, "location": null, "contact": null, "languages": null, "opening_dates": null, "opening_hours": [{"day": "tuesday", "opens": "10:00", "closes": "16:00"}, {"day": "wednesday", "opens": "10:00", "closes": "16:00"}, {"day": "friday", "opens": "10:00", "closes": "16:00"}], "availability": {"drop_in": true, "appointments": false}, "inventory": null, "access": null, "parent_organization": null, "links": null, "notes": null, "active": null, "source": {"source": "dc_district", "id": "e2d5625b5abe386bdc411cf1f6aad670", "fetched_from_uri": "https://coronavirus.dc.gov/vaccinatedc", "fetched_at": "2021-05-07T04:22:13.256079", "published_at": null, "data": {"Walk-Up Site": "Kenilworth Rec Center", "Address": "4321 Ord St, NE", "Normal Days / Hours": "Tues/Wed/Fri  \n10am-4pm", "Vaccine": "Moderna"}}}
```

## Before Opening a PR
- [ ✅ ] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [ ✅ ] I ran auto-formatting: `poetry run tox -e lint-fix`

### CODE REVIEW

**Review by bryanculbertson — APPROVED** [review]
This is some spectacular date parsing! I am approving, but can you rebase and fix the conflicting files?

If you can't get to it then I can try

**Comment by rascalking** [comment]
I'm not sure how to rebase when the PR is already started, so I went with a pickup merge.

**Comment by rascalking** [comment]
It looks like we hit a network hiccup while the checks were running, and short of a null commit, I'm not sure how to trigger them to rerun.

**Comment by bryanculbertson** [comment]
@rascalking I triggered a run-run

**Comment by bryanculbertson** [comment]
Merged!

**Pull request merged**
