### PR TITLE
LA tableau

### LINKED ISSUE #94: fetch tableau from Louisiana
[learn our pipeline: fetch](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#fetch)

Fetch data from: https://public.tableau.com/profile/lee.mendoza#!/vizhome/pharmacies_desktop/Pharmacies_desktop

Put your script in a file named: `la/tableau/fetch.py` (or `fetch.sh`, etc.)

Store it (without processing) in a new file created in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the fetch stage and how to get set up for development!

### Tips

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest fetch la/tableau
    ```

### PR DESCRIPTION
**Pull request by cdjj**
# 

| Key Details |
|-|
| Resolves #94 
State: LA |
Site: Louisiana Department of Health Tableau |

## Notes
Kudos to @krouskop and @nuchi for figuring out how to extract JSON from the site.

## Data sample
```json
3339663;{"sheetName":"Pharmacies_desktop","layoutId":"10601967672443134028","newSessionId":"48AA9CEF3D1C40B288695149E8FDC864-0:0","isDeferredBootstrap":true,"workbookLocale":"en_US","allowSubscriptions":true,"allowSubscribeOnDataPresent":true,"repositoryUrl":"pharmacies_desktop/Pharmacies_desktop","worldUpdate":{"applicationPresModel":{"renderMode": "render-mode-client","workbookPresModel":{"dashboardPresModel":{"sheetPath":{"sheetName": "Pharmacies_desktop","isDashboard": true},
```

## Before Opening a PR
- [X] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [X] I ran auto-formatting: `poetry run tox -e lint-fix`

### CODE REVIEW

**Comment by cdjj** [comment]
Huh, SuperLlinter's giving this unhelpful output:

```
2021-04-27 03:37:33 [ERROR]   Found errors in [editorconfig-checker] linter!
2021-04-27 03:37:33 [ERROR]   Error code: 1. Command output:
------
vaccine_feed_ingest/runners/la/tableau/fetch.sh:
	Wrong line endings or new final newline

1 errors found
------
2021-04-27 03:37:35 [INFO]   
2021-04-27 03:37:35 [INFO]   ----------------------------------------------
2021-04-27 03:37:35 [INFO]   ----------------------------------------------
2021-04-27 03:37:35 [INFO]   Linting [SHELL_SHFMT] files...
2021-04-27 03:37:35 [INFO]   ----------------------------------------------
2021-04-27 03:37:35 [INFO]   ----------------------------------------------
2021-04-27 03:37:35 [INFO]   ---------------------------
2021-04-27 03:37:35 [INFO]   File:[vaccine_feed_ingest/runners/la/tableau/fetch.sh]
2021-04-27 03:37:35 [ERROR]   Found errors in [shfmt] linter!
2021-04-27 03:37:35 [ERROR]   Error code: 1. Command output:
------
--- vaccine_feed_ingest/runners/la/tableau/fetch.sh.orig
+++ vaccine_feed_ingest/runners/la/tableau/fetch.sh
------
```

**Comment by yotann** [comment]
> ```
> 2021-04-27 03:37:33 [ERROR]   Found errors in [editorconfig-checker] linter!
> 2021-04-27 03:37:33 [ERROR]   Error code: 1. Command output:
> ------
> vaccine_feed_ingest/runners/la/tableau/fetch.sh:
> 	Wrong line endings or new final newline
> ```

There's a missing newline at the end of the file.

> ```
> 2021-04-27 03:37:35 [INFO]   File:[vaccine_feed_ingest/runners/la/tableau/fetch.sh]
> 2021-04-27 03:37:35 [ERROR]   Found errors in [shfmt] linter!
> ```

If you run `shfmt -w vaccine_feed_ingest/runners/la/tableau/fetch.sh` it will probably fix this.

**Comment by cdjj** [comment]
Hmm, I'd've expected the diff output to have an empty line there.  Oh well, added and let's see if the linter likes that any better.  Thanks, @yotann!

**Comment by cdjj** [comment]
Now it's complaining about the terminal newline:

```
2021-04-27 03:54:19 [INFO]   File:[vaccine_feed_ingest/runners/la/tableau/fetch.sh]
2021-04-27 03:54:19 [ERROR]   Found errors in [shfmt] linter!
2021-04-27 03:54:19 [ERROR]   Error code: 1. Command output:
------
--- vaccine_feed_ingest/runners/la/tableau/fetch.sh.orig
+++ vaccine_feed_ingest/runners/la/tableau/fetch.sh
@@ -18,4 +18,3 @@
     -H 'accept: application/json' \
     -d 'sheet_id=Pharmacies_desktop' \
     -o "${output_dir}/tableau.json"
-
------
```

**Comment by yotann** [comment]
I think you added two newlines instead of one, so now there's a blank line? At least, that's what it looks like in the "Files changed" tab.

**Comment by cdjj** [comment]
There was one blank line at the end of the original file, then I added another.  Trying removing both to see if that helps....

**Review by eliblock — COMMENTED** [review]
Impressive work from all the involved contributors to get this data!

I'm going to reply on #94 - from looking at the output here, I'm not sure this approach will lead to data that we're going to be able to parse (though I'd be happy to be proven wrong).

**Comment by cdjj** [comment]
Should we go ahead and merge this, so that we can get #234 in as well?

**Comment by eliblock** [comment]
Apologies - we've been doing some maintenance on downstream pipelines today so I haven't gotten around to reviewing/merging code. Merging this one now!

**Pull request merged**
