### PR TITLE
Parse fl/state

### LINKED ISSUE #403: parse fl/state
[learn our pipeline: parse](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#parse)

Blocked by #376

Parse existing data into [`.ndjson`](http://ndjson.org/).

Read all files in the directory passed as the second argument (`sys.argv[2]`), convert them to `.ndjson`, and then output them to new files in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the parse stage and how to get set up for development!

### Tips

1. Fetch data for this site before you start developing:
    ```sh
    poetry run vaccine-feed-ingest fetch fl/state
    ```

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest parse fl/state
    ```

### Example
[Fetched files for `md/arcgis`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/md/arcgis/raw) are converted to [parsed files](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/md/arcgis/parsed)

### PR DESCRIPTION
**Pull request by shajith**
# Parse state dataset for FL

| Key Details |
|-|
| Resolves #403 |
State: FL |
Site: state |

## Data sample

```json
{"id": "34416", "title": "Southern Internal Medicine", "address": "404 NW Hall of Fame Dr", "source": "manual", "content": "", "location": {"icon": "https://floridahealthcovid19.gov/wp-content/plugins/wp-google-map-gold/assets/images/default_marker.png", "lat": "30.18410951353843", "lng": "-82.69534913079957", "city": "Lake City", "state": "FL", "country": "United States", "onclick_action": "marker", "redirect_custom_link": "", "marker_image": "/wp-content/themes/wordpress-template/assets/images/pin_orange.png", "open_new_tab": "yes", "postal_code": "32055", "draggable": false, "infowindow_default_open": false, "animation": "", "infowindow_disable": true, "zoom": 5, "extra_fields": {"%ef%bb%bfcounty-name": "", "sponsored-by": "Healthcare", "partners": "", "sunday": "", "monday": "", "tuesday": "", "wednesday": "", "thursday": "", "friday": "", "saturday": "", "antibody": "", "antigen": "", "diagnostic": "", "rapid": "", "appointment-required": "", "physicians-order-required": "", "screening-required": "", "type-of-center": "", "additional-information": "", "website-url": "", "name": "", "title": "", "email": "", "phone": "", "county-name": "", "hide-address": "", "physician-order-required": "", "weeklycheck": "", "hideaddress": "", "county": "Columbia", "hours-of-operation": "", "website": "", "weekly-check": "", "category": "", "operational": "", "status": "", "address-line-2": "", "item-type": "", "path": "", "%ef%bb%bfstatus": "", "%ef%bb%bfupdate": "", "update": "", "%ef%bb%bfweeklycheck": "", "%ef%bb%bf": "", "listorder": 0}}, "categories": [{"id": "2", "name": "vaccine sites", "type": "category", "extension_fields": false, "icon": "https://floridahealthcovid19.gov/wp-content/plugins/wp-google-map-gold/assets/images/default_marker.png"}], "custom_filters": [], "custom_html": "<div class=\"wpgmp_locations\">\n\t<div class=\"location--primary\">\n\t\t<div class=\"title\">\n\t\t\t<a href=\"javascript:void(0)\" class=\"place_title\" data-zoom=\"4\" data-marker=\"34416\">Southern Internal Medicine</a><br>\n\t\t\t\t\t\t\t<div class=\"sponsored-by\">\n\t\t\t\t\tHealthcare\t\t\t\t</div>\n\t\t\t\n\t\t\t\t\t\t\t<div class=\"address\">\n\t\t\t\t\t<div class=\"pin\">\n\t\t\t\t\t\t<img src=\"/wp-content/themes/wordpress-template/assets/images/pin_orange.png\" alt=\"\">\n\t\t\t\t\t</div>\n\t\t\t\t\t\n\t\t\t\t\t<div class=\"link\">\n\t\t\t\t\t\t<a target='_blank' title='Open in Google Maps' href='https://www.google.com/maps/search/?api=1&query=404+NW+Hall+of+Fame+Dr+Lake+City+FL+32055' class='address_link'>404 NW Hall of Fame Dr, Lake City, FL 32055</a>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\n\t\t\t\t\t\t\t\t\t</div>\n\n\t\t<div class=\"open-close\">\n\t\t\t<a href=\"#\" class=\"open-close-link do-open\" data-for-marker=\"34416\">See More Information</a>\n\t\t\t<a href=\"#\" class=\"open-close-link do-close\" data-for-marker=\"34416\">Show Less Information</a>\n\t\t</div>\n\t</div>\n\n\t<div class=\"location--secondary\" data-for-marker=\"34416\">\n\t\t<div class=\"secondary-inner\">\n\t\t\t<div class=\"details\">\n\t\t\t\t<div class=\"left\">\n\t\t\t\t\t\t\t\t\t</div>\n\n\t\t\t\t<div class=\"right\">\n\t\t\t\t\t<div class=\"contact-info\">\n\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t<div class=\"bottom\">\n\t\t\t\t\t</div>\n\t</div>\n</div>"}
{"id": "37325", "title": "Walmart Inc", "address": "1800 NE 12TH AVE", "source": "manual", "location": {"icon": "https://floridahealthcovid19.gov/wp-content/plugins/wp-google-map-gold/assets/images/default_marker.png", "lat": "29.6640051", "lng": "-82.30078139999999", "city": "Gainesville", "state": "FL", "country": "United States", "onclick_action": "marker", "marker_image": "/wp-content/themes/wordpress-template/assets/images/pin_orange.png", "postal_code": "32641", "draggable": false, "infowindow_default_open": false, "infowindow_disable": true, "zoom": 5, "extra_fields": {"sponsored-by": "Walmart Inc", "additional-information": "", "county": "Alachua", "hours-of-operation": "By appointment", "website": "https://www.walmart.com/covidvaccine", "status": "", "listorder": 0}}, "categories": [{"id": "2", "name": "vaccine sites", "type": "category", "extension_fields": false, "icon": "https://floridahealthcovid19.gov/wp-content/plugins/wp-google-map-gold/assets/images/default_marker.png"}], "custom_html": "<div class=\"wpgmp_locations\">\n\t<div class=\"location--primary\">\n\t\t<div class=\"title\">\n\t\t\t<a href=\"javascript:void(0)\" class=\"place_title\" data-zoom=\"4\" data-marker=\"37325\">Walmart Inc</a><br>\n\t\t\t\t\t\t\t<div class=\"sponsored-by\">\n\t\t\t\t\tWalmart Inc\t\t\t\t</div>\n\t\t\t\n\t\t\t\t\t\t\t<div class=\"address\">\n\t\t\t\t\t<div class=\"pin\">\n\t\t\t\t\t\t<img src=\"/wp-content/themes/wordpress-template/assets/images/pin_orange.png\" alt=\"\">\n\t\t\t\t\t</div>\n\t\t\t\t\t\n\t\t\t\t\t<div class=\"link\">\n\t\t\t\t\t\t<a target='_blank' title='Open in Google Maps' href='https://www.google.com/maps/search/?api=1&query=1800+NE+12TH+AVE+Gainesville+FL+32641' class='address_link'>1800 NE 12TH AVE, Gainesville, FL 32641</a>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\n\t\t\t\t\t\t\t\t\t<br><a href=\"https://www.walmart.com/covidvaccine\" title='Open Location Website' target='_blank'>Website</a>\n\t\t\t\t\t\t\t\t\t</div>\n\n\t\t<div class=\"open-close\">\n\t\t\t<a href=\"#\" class=\"open-close-link do-open\" data-for-marker=\"37325\">See More Information</a>\n\t\t\t<a href=\"#\" class=\"open-close-link do-close\" data-for-marker=\"37325\">Show Less Information</a>\n\t\t</div>\n\t</div>\n\n\t<div class=\"location--secondary\" data-for-marker=\"37325\">\n\t\t<div class=\"secondary-inner\">\n\t\t\t<div class=\"details\">\n\t\t\t\t<div class=\"left\">\n\t\t\t\t\t\t\t\t\t\t\t<strong>Hours:</strong>\n\t\t\t\t\t\t<br>By appointment\t\t\t\t\t\t\t\t\t</div>\n\n\t\t\t\t<div class=\"right\">\n\t\t\t\t\t<div class=\"contact-info\">\n\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t<div class=\"bottom\">\n\t\t\t\t\t</div>\n\t</div>\n</div>"}
{"id": "37326", "title": "Southeastern Grocers", "address": "20303 N US HIGHWAY 441", "source": "manual", "location": {"icon": "https://floridahealthcovid19.gov/wp-content/plugins/wp-google-map-gold/assets/images/default_marker.png", "lat": "29.8407274", "lng": "-82.6012331", "city": "High Springs", "state": "FL", "country": "United States", "onclick_action": "marker", "marker_image": "/wp-content/themes/wordpress-template/assets/images/pin_orange.png", "postal_code": "32643", "draggable": false, "infowindow_default_open": false, "infowindow_disable": true, "zoom": 5, "extra_fields": {"sponsored-by": "Southeastern Grocers", "additional-information": "", "county": "Alachua", "hours-of-operation": "By appointment", "website": "", "status": "", "listorder": 0}}, "categories": [{"id": "2", "name": "vaccine sites", "type": "category", "extension_fields": false, "icon": "https://floridahealthcovid19.gov/wp-content/plugins/wp-google-map-gold/assets/images/default_marker.png"}], "custom_html": "<div class=\"wpgmp_locations\">\n\t<div class=\"location--primary\">\n\t\t<div class=\"title\">\n\t\t\t<a href=\"javascript:void(0)\" class=\"place_title\" data-zoom=\"4\" data-marker=\"37326\">Southeastern Grocers</a><br>\n\t\t\t\t\t\t\t<div class=\"sponsored-by\">\n\t\t\t\t\tSoutheastern Grocers\t\t\t\t</div>\n\t\t\t\n\t\t\t\t\t\t\t<div class=\"address\">\n\t\t\t\t\t<div class=\"pin\">\n\t\t\t\t\t\t<img src=\"/wp-content/themes/wordpress-template/assets/images/pin_orange.png\" alt=\"\">\n\t\t\t\t\t</div>\n\t\t\t\t\t\n\t\t\t\t\t<div class=\"link\">\n\t\t\t\t\t\t<a target='_blank' title='Open in Google Maps' href='https://www.google.com/maps/search/?api=1&query=20303+N+US+HIGHWAY+441+High+Springs+FL+32643' class='address_link'>20303 N US HIGHWAY 441, High Springs, FL 32643</a>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\n\t\t\t\t\t\t\t\t\t</div>\n\n\t\t<div class=\"open-close\">\n\t\t\t<a href=\"#\" class=\"open-close-link do-open\" data-for-marker=\"37326\">See More Information</a>\n\t\t\t<a href=\"#\" class=\"open-close-link do-close\" data-for-marker=\"37326\">Show Less Information</a>\n\t\t</div>\n\t</div>\n\n\t<div class=\"location--secondary\" data-for-marker=\"37326\">\n\t\t<div class=\"secondary-inner\">\n\t\t\t<div class=\"details\">\n\t\t\t\t<div class=\"left\">\n\t\t\t\t\t\t\t\t\t\t\t<strong>Hours:</strong>\n\t\t\t\t\t\t<br>By appointment\t\t\t\t\t\t\t\t\t</div>\n\n\t\t\t\t<div class=\"right\">\n\t\t\t\t\t<div class=\"contact-info\">\n\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\n\t\t<div class=\"bottom\">\n\t\t\t\t\t</div>\n\t</div>\n</div>"}
```

## Before Opening a PR
- [ ] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [ ] I ran auto-formatting: `poetry run tox -e lint-fix`

### CODE REVIEW

**Comment by bryanculbertson** [comment]
@shajith Can you explain the utility of including the `custom_html` field in the parsed json? Also, can you also explain what is in `custom_html`?

My intention was for the parse stage to do all of the html parsing, and then the normalize stage was just re-working the resulting JSON to our NormalizeLocation schema.

I would like to know if this model doesn't work here, or you were actually just planning on ignoring `custom_html` field in normalize.

**Comment by shajith** [comment]
@bryanculbertson `custom_html` just happens to be a key included in the raw JSON in the source data - I can strip that out. I haven't processed the JSON beyond extracting it out of the original data in this pass - should I be doing cleanup or combining of fields in the `parse` stage? I wasn't sure if that's something I can do in `normalize` next, but happy to do more in this phase is that's the better practice.

**Comment by bryanculbertson** [comment]
@shajith Ah, I see, I thought you were copying over the html from the page. This is fine since that HTML was in the original record.

If you do end up needing to parse that HTML with BeautifulSoup, then I would prefer if you did that parsing in the parse stage and converted it into fields on the JSON record.

Approving and Merging!

**Review by bryanculbertson — APPROVED** [review]

**Comment by shajith** [comment]
Thanks @bryanculbertson! Eye-balling the payload, everything rendered in that HTML bit is already available as keys in the rest of the record, so I should be good. On to normalize now!

**Pull request merged**
