### PR TITLE
Add IL juvare fetcher

### LINKED ISSUE #150: fetch juvare from Illinois
[learn our pipeline: fetch](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#fetch)

Fetch data from: https://covidvaccination.dph.illinois.gov/

Put your script in a file named: il/juvare/fetch.sh

Store it (without processing) in a new file created in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the fetch stage and how to get set up for development!

### Tips

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest fetch <state>/<site>
    ```

### PR DESCRIPTION
**Pull request by yotann**
Scrapes the Illinois Department of Public Health vaccine appointment form at <https://covidvaccination.dph.illinois.gov/>. This form lists sites with available appointments, using [Juvare](https://www.juvare.com).

NOTE: it may be possible to scrape additional information, like phone numbers, by following the link for each site. Example: <https://archive.md/CRuvx>.

Fixes #150.

### CODE REVIEW

**Review by eliblock — CHANGES_REQUESTED** [review]
Thank you for kicking off this work - I'm excited to get this data into the pipeline!

When I try running this locally (e.g., using `poetry run vaccine-feed-ingest fetch il/juvare`), it looks like the regex does not pick up the `buildId`, so the json comes back empty. Could you take another look at this?

**Comment by yotann** [comment]
Must be because I was relying on [GNU-only sed features](https://unix.stackexchange.com/a/131940). Try the new version, I tested it with FreeBSD sed.

**Review by tmb — APPROVED** [review]
Looks good! Everything works on my end.

**Review by eliblock — APPROVED** [review]
Thank you for the update!

**Pull request merged**
