### PR TITLE
(pt 1) support extraction of additional providers #254

### PR DESCRIPTION
**Pull request by shashank025**
| Key Details |
|-|
| Addresses #254  |
State:  |
Site:  |

## Notes

This PR uses [a sample CSV](https://github.com/CAVaccineInventory/vaccine-feed-ingest/files/6388621/select-name-from-location-orded0ba3a.csv) provided on #254 that contains about 10K rows of parsed provider info to improve coverage of providers while extracting a provider id and name from data sources. Specifically, that CSV was sorted alphabetically, and support was added for providers in that sorted list whose names start from **_A_** through **_K_**.

This is the first in a series of planned steps to improve coverage. Upcoming plans:

1. Add the newly identified providers to the [schema repo](https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema)
2. Support other providers (**_L_** through **_Z_**) from the provided CSV.
3. Add a simple helper script that shows a measure of **_coverage_** by applying this script to a specified input file. Basically, it will spit out how many of the input rows had a matching provider name + id extracted. This helper can be used to track improvements to coverage over time.
4. [Optimization] Rearrange the regexes in `provider_id_from_name()` in the order of expected national coverage, so that a national chain like COSTCO or WALGREENS with heavy coverage can be matched first, and the function can then exit early.

### Update

This PR also updates the `provider_id_from_name()` method to return a `VaccineProvider` (previously `str`).

## Data sample

As a sanity check, I ran:

```
poetry run vaccine-feed-ingest all-stages ok/vaccinate_gov
poetry run vaccine-feed-ingest all-stages ca/sf_gov
```
and examined the normalized outputs.

## Before Opening a PR
- [X] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [X] I ran auto-formatting: `poetry run tox -e lint-fix`

### CODE REVIEW

**Review by nschiefer — COMMENTED** [review]
This looks great! If it's not too much hassle, I'd love to add all of the new providers to the schema before we merge this, just so that we have validation in place to verify that they are the same in both repos.

Super excited to get this change in!

**Comment by shashank025** [comment]
> This looks great! If it's not too much hassle, I'd love to add all of the new providers to the schema before we merge this, just so that we have validation in place to verify that they are the same in both repos.

Let me do that first, then.

**Comment by shashank025** [comment]
Created PR in the other repo for adding these providers: https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema/pull/19

**Comment by shashank025** [comment]
Need to make one more update for this is ready for merge.

**Comment by eliblock** [comment]
@shashank025 [`vaccine-feed-ingest-schema` `v1.2.1`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema/releases/tag/1.2.1) has been released with the added enums!

Could you add to this PR:
* bump the version of the schema (do this by updating the version in `pyproject.toml` and then running `poetry update v
accine-feed-ingest-schema`
* use the new enum values rather than the strings in this file! You can see a sample of how to do this [here](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/4d1eb5b0250f8652d04f7eee0f6b64b72dce7cd4/vaccine_feed_ingest/runners/az/pinal_ph_clinics_gov/normalize.py#L63).

**Comment by shashank025** [comment]
> @shashank025 [`vaccine-feed-ingest-schema` `v1.2.1`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema/releases/tag/1.2.1) has been released with the added enums!

Cool!

> Could you add to this PR:
> 
>     * bump the version of the schema (do this by updating the version in `pyproject.toml` and then running `poetry update v accine-feed-ingest-schema`
> 
>     * use the new enum values rather than the strings in this file! You can see a sample of how to do this [here](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/4d1eb5b0250f8652d04f7eee0f6b64b72dce7cd4/vaccine_feed_ingest/runners/az/pinal_ph_clinics_gov/normalize.py#L63).

Ahh, understood. Will do!

**Comment by shashank025** [comment]
Hmm, I just rebased against main, and I am seeing a test failure when I run:

```
poetry run tox -q -e test
```

The error is:

```
E   ModuleNotFoundError: No module named 'url_normalize'
```

which makes me think the issue is with some poetry config involving a new module `url_normalize` that was added in https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/349 - but I don't see why this should fail because I do see that both my `pyproject.toml` and `poetry.lock` have been updated with this new dependency.

Investigating some more ...

**Full Stack Trace:**


```
======================================================================================================= test session starts ========================================================================================================
platform darwin -- Python 3.9.4, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
cachedir: .tox/test/.pytest_cache
rootdir: /Users/shashankr/projects/vaccine-feed-ingest
plugins: anyio-2.2.0
collected 4 items / 1 error / 3 selected

============================================================================================================== ERRORS ==============================================================================================================
____________________________________________________________________________________ ERROR collecting tests/utils/test_provider_id_from_name.py ____________________________________________________________________________________
ImportError while importing test module '/Users/shashankr/projects/vaccine-feed-ingest/tests/utils/test_provider_id_from_name.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/utils/test_provider_id_from_name.py:1: in <module>
    from vaccine_feed_ingest.utils.normalize import provider_id_from_name
vaccine_feed_ingest/utils/normalize.py:7: in <module>
    import url_normalize
E   ModuleNotFoundError: No module named 'url_normalize'
===================================================================================================== short test summary info ======================================================================================================
ERROR tests/utils/test_provider_id_from_name.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================================================= 1 error in 1.85s =========================================================================================================
ERROR: InvocationError for command /usr/local/bin/poetry run pytest tests (exited with code 2)
_____________________________________________________________________________________________________________ summary ______________________________________________________________________________________________________________
ERROR:   test: commands failed
```

**Comment by shashank025** [comment]
Ah, perhaps I need to do:

```
poetry update url-normalize
```

**Comment by shashank025** [comment]
Didn't help. Did a poetry update after bumping the schema version, which resulted in installing url-normalize:

```
$ poetry update vaccine-feed-ingest-schema
Updating dependencies
Resolving dependencies... (297.9s)

Writing lock file

Package operations: 8 installs, 11 updates, 0 removals

  • Installing matplotlib-inline (0.1.2)
  • Updating cachetools (4.2.1 -> 4.2.2)
  • Updating ipython (7.22.0 -> 7.23.0)
  • Updating google-auth (1.29.0 -> 1.30.0)
  • Updating babel (2.9.0 -> 2.9.1)
  • Installing dnspython (2.1.0)
  • Installing email-validator (1.1.2)
  • Updating jupyterlab-server (2.4.0 -> 2.5.0)
  • Updating typing-extensions (3.7.4.3 -> 3.10.0.0)
  • Updating et-xmlfile (1.0.1 -> 1.1.0)
  • Updating google-cloud-storage (1.37.1 -> 1.38.0)
  • Installing lxml (4.6.3)
  • Installing html5lib (1.1)
  • Updating pathy (0.4.0 -> 0.5.2)
  • Installing pykml (0.2.0)
  • Updating python-dotenv (0.17.0 -> 0.17.1)
  • Installing tableauscraper (0.1.11)
  • Installing url-normalize (1.4.3)
  • Updating vaccine-feed-ingest-schema (0.2.1 -> 1.2.1)
```

but running the tests:

```
poetry run tox -q -e test
```

still fails.

**Comment by shashank025** [comment]
Tried to do a sanity check by running:

```
$ poetry run vaccine-feed-ingest all-stages nv/immunizenevada_org
```

and I'm seeing a normalization error:

```
2021-05-01T21:46:53-0700 INFO:stages/ingest.py:Normalizing nv/immunizenevada_org and saving normalized output to /var/folders/04/446hhxbj52x3yrtv1g7dcdfm0000gn/T/tmpzxaw70iz_normalize_nv_immunizenevada_org/output
Traceback (most recent call last):
  File "/Users/shashankr/projects/vaccine-feed-ingest/vaccine_feed_ingest/runners/nv/immunizenevada_org/normalize.py", line 145, in <module>
    sys.exit(main())
  File "/Users/shashankr/projects/vaccine-feed-ingest/vaccine_feed_ingest/runners/nv/immunizenevada_org/normalize.py", line 138, in main
    normalized_site = normalize(site, parsed_at_timestamp)
  File "/Users/shashankr/projects/vaccine-feed-ingest/vaccine_feed_ingest/runners/nv/immunizenevada_org/normalize.py", line 95, in normalize
    address=_get_address(site["address"]),
  File "/Users/shashankr/projects/vaccine-feed-ingest/vaccine_feed_ingest/runners/nv/immunizenevada_org/normalize.py", line 44, in _get_address
    result = schema.Address(
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Address
state
  value is not a valid enumeration member; permitted: 'AL', 'AK', 'AS', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'GU', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'MP', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'VI', 'WA', 'WV', 'WI', 'WY' (type=type_error.enum; enum_values=[<State.ALABAMA: 'AL'>, <State.ALASKA: 'AK'>, <State.AMERICAN_SAMOA: 'AS'>, <State.ARIZONA: 'AZ'>, <State.ARKANSAS: 'AR'>, <State.CALIFORNIA: 'CA'>, <State.COLORADO: 'CO'>, <State.CONNECTICUT: 'CT'>, <State.DELAWARE: 'DE'>, <State.DISTRICT_OF_COLUMBIA: 'DC'>, <State.FLORIDA: 'FL'>, <State.GEORGIA: 'GA'>, <State.GUAM: 'GU'>, <State.HAWAII: 'HI'>, <State.IDAHO: 'ID'>, <State.ILLINOIS: 'IL'>, <State.INDIANA: 'IN'>, <State.IOWA: 'IA'>, <State.KANSAS: 'KS'>, <State.KENTUCKY: 'KY'>, <State.LOUISIANA: 'LA'>, <State.MAINE: 'ME'>, <State.MARYLAND: 'MD'>, <State.MASSACHUSETTS: 'MA'>, <State.MICHIGAN: 'MI'>, <State.MINNESOTA: 'MN'>, <State.MISSISSIPPI: 'MS'>, <State.MISSOURI: 'MO'>, <State.MONTANA: 'MT'>, <State.NEBRASKA: 'NE'>, <State.NEVADA: 'NV'>, <State.NEW_HAMPSHIRE: 'NH'>, <State.NEW_JERSEY: 'NJ'>, <State.NEW_MEXICO: 'NM'>, <State.NEW_YORK: 'NY'>, <State.NORTH_CAROLINA: 'NC'>, <State.NORTH_DAKOTA: 'ND'>, <State.NORTHERN_MARIANA_IS: 'MP'>, <State.OHIO: 'OH'>, <State.OKLAHOMA: 'OK'>, <State.OREGON: 'OR'>, <State.PENNSYLVANIA: 'PA'>, <State.PUERTO_RICO: 'PR'>, <State.RHODE_ISLAND: 'RI'>, <State.SOUTH_CAROLINA: 'SC'>, <State.SOUTH_DAKOTA: 'SD'>, <State.TENNESSEE: 'TN'>, <State.TEXAS: 'TX'>, <State.UTAH: 'UT'>, <State.VERMONT: 'VT'>, <State.VIRGINIA: 'VA'>, <State.VIRGIN_ISLANDS: 'VI'>, <State.WASHINGTON: 'WA'>, <State.WEST_VIRGINIA: 'WV'>, <State.WISCONSIN: 'WI'>, <State.WYOMING: 'WY'>])
```

While that is alarming in itself, at least it tells me that parsing (which uses `provider_id_from_name`) is not broken, which leads me to think that the issue is with how we've configured **_tests_** to run...

**Comment by shashank025** [comment]
@eliblock helped me out. I had to clear my local **_tox_** cache like so:

```
rm -r .tox
```

and #351 will fix the normalization error that I posted above.

**Review by eliblock — APPROVED** [review]
Thank you for adding this - and for the matching change to `vaccine-feed-ingest-schema`. It will greatly improve our data quality when this gets used!

**Comment by bryanculbertson** [comment]
Note that `tox -r` will recreate the tox venvs within tox

**Pull request merged**
