### PR TITLE
Fetch, Parse, and Normalize tx Memorial Hermann

### LINKED ISSUE #647: fetch tx/memorialherman
[learn our pipeline: fetch](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#fetch)

Fetch data from: https://memorialhermann.org/services/conditions/coronavirus/vaccine-walk-in-clinics

Put your script in a file named: `tx/memorialherman/fetch.py` (or `fetch.sh`, etc.)

Store it (without processing) in a new file created in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the fetch stage and how to get set up for development!

### Tips

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest fetch tx/memorialherman
    ```

### LINKED ISSUE #650: parse tx/memorialherman
[learn our pipeline: parse](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#parse)

Blocked by #647

Parse existing data into [`.ndjson`](http://ndjson.org/).

Read all files in the directory passed as the second argument (`sys.argv[2]`), convert them to `.ndjson`, and then output them to new files in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the parse stage and how to get set up for development!

### Tips

1. Fetch data for this site before you start developing:
    ```sh
    poetry run vaccine-feed-ingest fetch tx/memorialherman
    ```

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest parse tx/memorialherman
    ```

### Example
[Fetched files for `md/arcgis`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/md/arcgis/raw) are converted to [parsed files](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/md/arcgis/parsed)

### PR DESCRIPTION
**Pull request by ben-heil**
# 

| Key Details |
|-|
| Resolves #647 #650 #653|
State: tx |
Site: Memorial Hermann |

## Notes
~I plan on working on the normalize script some time tomorrow. Is there a standard way to handle lunch breaks in vaccine site times? Several of the sites in the current dataset have two open and close times: one in the morning, and one in the evening.~

This PR fetches, parses, and normalizes the data from Memorial Hermann. I ended up handling the lunch breaks by creating multiple OpenHour objects corresponding to individual days; let me know if you want me to handle that case differently.

## Data sample

Fetcher:
```html
<h3>Memorial Hermann-Texas Medical Center</h3>
<p><strong>Address</strong><br />
6411 Fannin Street<br />
Houston, TX 77030</p>
<p><strong>Walk-in Hours </strong><br />
Monday &ndash; Friday<br />
7:30 a.m. - 10:30 a.m.<br />
2:30 p.m. - 5:30 p.m.</p>
<p><strong>Vaccine</strong><br />
Pfizer</p>
<p><strong>Location Details </strong><br />
Located in the Memorial Hermann-Texas Medical Center Atrium. Please park in valet (free for patients only) at 6411 Fannin Street and proceed to the ground floor of the Atrium. <a href="/locations/texas-medical-center" title="View Location Page">View Location Page &raquo;</a></p>
<a name="gh"></a>
```
Parser:
```json
{"sites": [{"name": ["Memorial Hermann-Texas Medical Center"], "address": "6411 Fannin Street\nHouston, TX 77030", "hours": [["Monday \u2013 Friday", ["7:30 a.m. - 10:30 a.m.", "2:30 p.m. - 5:30 p.m."]]], "vaccine": "Pfizer", "location_details": "Located in the Memorial Hermann-Texas Medical Center Atrium. Please park in valet (free for patients only) at 6411 Fannin Street and proceed to the ground floor of the Atrium."}, {"name": ["Memorial Hermann Greater Heights Hospital"], "address": "1635 North Loop West\nHouston, TX 77008", "hours": [["Monday \u2013 Friday", ["7:30 a.m. - 10:30 a.m.", "2:30 p.m. - 5:30 p.m."]]], "vaccine": "Pfizer", "location_details": "Located in Conference Rooms C & D. Enter the hospital through the South Tower Circle Drive Entrance and the conference room is on the left."},}
```

Normalizer:
```json
{"id": "tx_memorialhermann:memorial_hermann_texas_medical_centerhouston", "name": "Memorial Hermann-Texas Medical Center", "address": {"street1": "6411 Fannin Street", "street2": null, "city": "Houston", "state": "TX", "zip": "77030"}, "location": null, "contact": null, "languages": null, "opening_dates": null, "opening_hours": [{"day": "monday", "opens": "07:30", "closes": "10:30"}, {"day": "tuesday", "opens": "07:30", "closes": "10:30"}, {"day": "wednesday", "opens": "07:30", "closes": "10:30"}, {"day": "thursday", "opens": "07:30", "closes": "10:30"}, {"day": "friday", "opens": "07:30", "closes": "10:30"}, {"day": "monday", "opens": "14:30", "closes": "17:30"}, {"day": "tuesday", "opens": "14:30", "closes": "17:30"}, {"day": "wednesday", "opens": "14:30", "closes": "17:30"}, {"day": "thursday", "opens": "14:30", "closes": "17:30"}, {"day": "friday", "opens": "14:30", "closes": "17:30"}], "availability": {"drop_in": true, "appointments": null}, "inventory": [{"vaccine": "pfizer_biontech", "supply_level": null}], "access": null, "parent_organization": null, "links": null, "notes": ["Located in the Memorial Hermann-Texas Medical Center Atrium. Please park in valet (free for patients only) at 6411 Fannin Street and proceed to the ground floor of the Atrium."], "active": null, "source": {"source": "tx_memorialhermann", "id": "memorial_hermann_texas_medical_centerhouston", "fetched_from_uri": "https://memorialhermann.org/services/conditions/coronavirus/vaccine-walk-in-clinics", "fetched_at": "2021-05-31T17:20:53.829096", "published_at": null, "data": {"name": ["Memorial Hermann-Texas Medical Center"], "address": "6411 Fannin Street\nHouston, TX 77030", "hours": [["Monday \u2013 Friday", ["7:30 a.m. - 10:30 a.m.", "2:30 p.m. - 5:30 p.m."]]], "vaccine": "Pfizer", "location_details": "Located in the Memorial Hermann-Texas Medical Center Atrium. Please park in valet (free for patients only) at 6411 Fannin Street and proceed to the ground floor of the Atrium."}}}
```

## Before Opening a PR
- [x] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [x] I ran auto-formatting: `poetry run tox -e lint-fix`

### CODE REVIEW

**Comment by MoralCode** [comment]
I did notice that GitHub only detected the first of the three issues you mentioned so i went ahead and linked the other two so merging this will close those issues too.

I can also confirm that `poetry run vaccine-feed-ingest all-stages tx/memorialhermann` runs  successfully on my machine in case that helps speed up the review process at all.

Great work and thanks for the contribution!

**Comment by ben-heil** [comment]
> I did notice that GitHub only detected the first of the three issues you mentioned so i went ahead and linked the other two so merging this will close those issues too.

Good catch! I forgot to check whether they linked correctly

**Comment by bryanculbertson** [comment]
@ben-heil
> This PR fetches, parses, and normalizes the data from Memorial Hermann. I ended up handling the lunch breaks by creating multiple OpenHour objects corresponding to individual days; let me know if you want me to handle that case differently.

Yep. This is the best way to handle lunch breaks. 

In case it is useful, the open hours schema is based on the one developed for schema.org  https://schema.org/OpeningHoursSpecification

**Review by bryanculbertson — APPROVED** [review]

**Comment by bryanculbertson** [comment]
Approved and merged. Thanks @MoralCode for reviewing!

**Pull request merged**
