### PR TITLE
Normalize Vaccinate NJ for NJ

### LINKED ISSUE #699: normalize nj/vaccinate_nj
[learn our pipeline: normalize](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#normalize)

Normalize existing [`.ndjson`](http://ndjson.org/) records into [the Vaccinate The States data schema](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Normalized-Location-Schema).

Read all files in the directory passed as the second argument (`sys.argv[2]`), transform each record into the normalized schema (filling in as much detail as possible), then output them to new files in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the normalize stage and how to get set up for development!

### Tips

1. Fetch and parse data for this site before you start developing:
    ```sh
    poetry run vaccine-feed-ingest fetch <state>/<site>
    poetry run vaccine-feed-ingest parse <state>/<site>
    ```

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest normalize <state>/<site>
    ```

### Example
[Parsed files for `ak/arcgis`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/nj/vaccinate_nj/parsed) are converted to [normalized files](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/nj/vaccinate_nj/normalized)

### PR DESCRIPTION
**Pull request by LWprogramming**
# 

| Key Details |
|-|
| Resolves #699 |
State: NJ |
Site: Vaccinate NJ |

## Notes
All issues resolved

## Data sample

```json
{"id": "vaccinate_nj:8465a5f6-9638-4cb8-9c88-d3612e7e8ee4", "name": "Adlers Pharmacy LTC", "address": {"street1": "100 Dobbs Lane Suite 205", "city": "Cherry Hill", "state": "NJ", "zip": "08034"}, "location": {"latitude": 39.8835179, "longitude": -75.00599559999999}, "languages": ["en"], "availability": {"drop_in": false, "appointments": true}, "active": true, "source": {"source": "vaccinate_nj", "id": "8465a5f6-9638-4cb8-9c88-d3612e7e8ee4", "fetched_from_uri": "https://c19vaccinelocatornj.info/api/v1/vaccine/locations/page", "fetched_at": "2021-05-31T17:31:39.460954", "published_at": "2021-04-09T16:21:06Z", "data": {"name": "Adlers Pharmacy LTC", "id": "8465a5f6-9638-4cb8-9c88-d3612e7e8ee4", "city": "Cherry Hill", "zipCode": "08034", "county": "Camden", "url": "https://covidvaccine.nj.gov", "type": "Pharmacy", "availabilityStatus": "Available", "availabilityChangedDate": "2021-04-10T23:37:58Z", "address": "100 Dobbs Lane Suite 205", "phone": null, "createdDate": "2021-04-10T23:36:08Z", "updatedDate": "2021-04-10T23:37:58Z", "scheduling": ["NJ VSS"], "lastCheckedDate": "2021-04-09T16:21:06Z", "eligibility": "State Wide", "geoCode": {"latitude": 39.8835179, "longitude": -75.00599559999999, "type": "ROOFTOP"}}}, "contact": [{"website": "https://covidvaccine.nj.gov"}]}
```

## Before Opening a PR
- [x] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [x] I ran auto-formatting: `poetry run tox -e lint-fix`

### CODE REVIEW

**Comment by MoralCode** [comment]
@LWprogramming Looking at the logs it seems as though it is complaining about extra or empty values that are being provided. heres the output from the CI run that seems to be more detailed than what you posted
```
2021-05-29T19:16:44+0000 WARNING:stages/ingest.py:Invalid source location in /tmp/tmpscoors6w_normalize_nj_vaccinate_nj/output/data.normalized.ndjson at line 1: b'{"id": "vaccinate_nj:e82968a6-570d-410b-be73-317a7d39f13b", "name": "Rite Aid #1360", "address": {"s'
2 validation errors for NormalizedLocation
contact -> 1 -> url
  extra fields not permitted (type=value_error.extra)
contact -> 1 -> __root__
  No values specified for Contact. (type=value_error)
```

**Comment by MoralCode** [comment]
> I'm also confused how to get the fetched_at field (see the TODO in the code) that the normalized schema specifies.

For that you can pretty much just use `datetime.datetime.utcnow().isoformat()`. That seems to be how other normalize.py scripts are written. If you prefer you can also just copy-paste one of those when creating a new normalizer so it gets taken care of for you next time

> Finally: the issue template I used here says that the input should be a directory and this script should potentially have to handle all the files in that directory, but as far as I know the parse stage only produces one data file per directory, correct?

I believe you are correct that the parser usually only emits one file but the normalizer is designed to handle many. I don't know for sure but i suspect that there may be data sources that split data across multiple files. This "check every fiie in the directory" behavior can also be copied from existing normalizers.


Hope that helps!

**Comment by LWprogramming** [comment]
I've fixed all the issues now and, pending CI & lint passing, should be ready for merge!

**Comment by MoralCode** [comment]
Awesome, I dont have permission to do the final approval, but I requested it from eli. Thanks for your contribution!

**Review by bryanculbertson — APPROVED** [review]

**Comment by bryanculbertson** [comment]
@LWprogramming I am approving and merging. If you have time for a followup PR, this could be improved by using the our `NormalizedLocation` pydantic schema. This will validate the locations as you build them to better track errors.

Look at `sf_gov` for an example of how to do this: https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/main/vaccine_feed_ingest/runners/ca/sf_gov/normalize.py

**Pull request merged**
