### PR TITLE
Added fetch for nc data

### PR DESCRIPTION
**Pull request by rreichman**
The _fetch.py_ script uses Selenium to collect data from the NC official website, by querying per NC zip code. The zip codes are collected through the requests library via a third party website. The script takes about 4 minutes to run on my personal computer and produces an html file for each zip code.

Solves issue #87

### CODE REVIEW

**Comment by Sebmaster** [comment]
@rreichman Did you see the API req to `https://myspot.nc.gov/api/get-vaccine-locations`? Is that missing some info that's available in the HTML? It seems to contain the info for all vaccination locations without any parameters.

**Comment by rreichman** [comment]
> @rreichman Did you see the API req to `https://myspot.nc.gov/api/get-vaccine-locations`? Is that missing some info that's available in the HTML? It seems to contain the info for all vaccination locations without any parameters.

@Sebmaster whew I was not aware of that. Did I miss it in the issue requirements? Anyway I switched to using it. Code is much much simpler now.

**Comment by eliblock** [comment]
@Sebmaster - thank you for sharing that API... we hadn't seen it yet (@rreichman that's why it was not in the issue comments).

Excited for the simpler code - particularly because it means we can get this merged without waiting for me to add the additional dependencies to our scraping infrastructure for selenium (which we'll do! but... not yet if it's not needed).

That said, it looks like this doesn't run right now using the CLI (try: `poetry run vaccine-feed-ingest all-stages nc/myspot_gov`). It looks like the file might need to be made executable (`chmod +x vaccine_feed_ingest/runners/nc/myspot_gov/fetch.py`), and the file might also need a python shebang (add `#!/usr/bin/env python3` as the first line). Could you please make sure the script runs using the `poetry run` command?

Once that's sorted out, this should be good to go!

**Comment by rreichman** [comment]
> @Sebmaster - thank you for sharing that API... we hadn't seen it yet (@rreichman that's why it was not in the issue comments).
> 
> Excited for the simpler code - particularly because it means we can get this merged without waiting for me to add the additional dependencies to our scraping infrastructure for selenium (which we'll do! but... not yet if it's not needed).
> 
> That said, it looks like this doesn't run right now using the CLI (try: `poetry run vaccine-feed-ingest all-stages nc/myspot_gov`). It looks like the file might need to be made executable (`chmod +x vaccine_feed_ingest/runners/nc/myspot_gov/fetch.py`), and the file might also need a python shebang (add `#!/usr/bin/env python3` as the first line). Could you please make sure the script runs using the `poetry run` command?
> 
> Once that's sorted out, this should be good to go!

Thanks @eliblock I added the python shebang and now it runs with the command _poetry run vaccine-feed-ingest fetch nc/myspot_gov_ without error though it doesn't indicate that it's putting the result in any output file. Any thoughts?

**Review by eliblock — APPROVED** [review]
Thank you for those fixes! This looks good to go!

What you're running into here is that our cli does not currently tell you where it's putting the data (I opened an issue about this, #170). That said, by default the output for this will go to to `./out/nc/myspot_gov/raw/<timestamp>/*`.

Here's a quick sample of the data you're getting:

```
{"code": 200, "message": "success", "records": [{"CVMS Scheduling": "F", "City": "Kernersville", "Event Location Id": "E-0000015", "County": "Forsyth", "latitude": "36.1122068", "Appointment Phone": "(336) 497-4511", "Pfizer": "", "Organization Name": "Kernersville Pharmacy LLC", "Street Address": "841 Old Winston Road", "Event Location": "", "State": "NC", "Start Date": "20210315 000000.000", "Web Address": "https://kernersvillepharmacy.com/", "End Date": "", "Provider Location Name": "Kernersville Pharmacy", ...
```

**Comment by rreichman** [comment]
> Thank you for those fixes! This looks good to go!
> 
> What you're running into here is that our cli does not currently tell you where it's putting the data (I opened an issue about this, #170). That said, by default the output for this will go to to `./out/nc/myspot_gov/raw/<timestamp>/*`.
> 
> Here's a quick sample of the data you're getting:
> 
> ```
> {"code": 200, "message": "success", "records": [{"CVMS Scheduling": "F", "City": "Kernersville", "Event Location Id": "E-0000015", "County": "Forsyth", "latitude": "36.1122068", "Appointment Phone": "(336) 497-4511", "Pfizer": "", "Organization Name": "Kernersville Pharmacy LLC", "Street Address": "841 Old Winston Road", "Event Location": "", "State": "NC", "Start Date": "20210315 000000.000", "Web Address": "https://kernersvillepharmacy.com/", "End Date": "", "Provider Location Name": "Kernersville Pharmacy", ...
> ```

Cool, thanks!

**Pull request merged**
